{ config, lib, pkgs, ... }:

let
  # Obsidian needs only TCP, so the local HTTP proxy is enough and it stays out
  # of the VPN capture namespace. The flag scopes the proxy to this process,
  # never the session. Vaults and session state remain machine-local.
  obsidian = pkgs.obsidian.override {
    commandLineArgs = lib.optionalString config.dotfiles.localProxy.enable
      "--proxy-server=http://127.0.0.1:3128";
  };

  theme = config.dotfiles.theme;

  # Obsidian looks for `<vault>/.obsidian/themes/<name>/theme.css`, where the
  # directory name is the manifest's name, so the theme is called "Dotfiles"
  # and a vault is linked to it once. Home Manager repoints these two files at
  # every generation; the link inside the vault never has to change.
  themeDir = "${theme.dataDir}/obsidian";
  themeName = "Dotfiles";

  # Every declared repository is a candidate vault; whether it is one is only
  # knowable at run time, from the .obsidian directory Obsidian creates. They
  # stay relative here and are resolved against $HOME by the check itself,
  # which is what the notice runs in.
  repositories = lib.attrNames config.dotfiles.repositories;
in
{
  home.packages = [ obsidian ];

  home.file."${themeDir}/theme.css".source = pkgs.writeText "obsidian-theme.css"
    (import ../theme/obsidian-theme.nix { inherit lib; } (theme.forApp "obsidian"));

  home.file."${themeDir}/manifest.json".source = pkgs.writeText "manifest.json"
    (builtins.toJSON {
      name = themeName;
      version = "1.0.0";
      minAppVersion = "1.6.0";
      author = "Generated by modules/theme from the palette in home.nix";
    });

  # Obsidian reads a theme at startup and does not reload it through the
  # symlink, so a switch shows at the next launch. Linking a vault cannot be
  # done here: a vault is machine-local, may be anywhere, and Obsidian has to
  # have created its .obsidian directory first.
  dotfiles.theme.apps.obsidian = {
    label = "Obsidian";
    apply = "restart";
    setup = "link ${themeDir} into <vault>/.obsidian/themes/${themeName}, then pick ${themeName} under Settings → Appearance";
    check = ''
      for name in ${lib.escapeShellArgs repositories}; do
        vault=$HOME/$name
        [[ -d $vault/.obsidian ]] || continue
        [[ -e $vault/.obsidian/themes/${themeName} || -L $vault/.obsidian/themes/${themeName} ]] && continue
        printf '%s has no %s link\n' "''${name##*/}" ${lib.escapeShellArg themeName}
      done
    '';
  };

  # Its Electron's sandbox needs a user namespace on Ubuntu, or Obsidian aborts
  # at startup. Nixpkgs' Electron is shared with Vesktop, and so is the profile.
  dotfiles.apparmor.usernsAllowances."electron-${lib.versions.major pkgs.electron.version}" = {
    executable = "${pkgs.electron.unwrapped}/libexec/electron/electron";
    usedBy = [ obsidian ];
  };
}
