{ lib }:

# A Sublime Text color scheme from a resolved theme. Sublime rereads a scheme
# in Packages/User when the file changes, which is why this is written as an
# ordinary file rather than a store symlink. The scheme keeps the stable name
# "Dotfiles", so Preferences never has to change.
#
# Syntax takes the semantic roles where they say something — comments are
# muted, strings succeed, keywords err — and the palette's brighter ANSI hues
# where the distinction is only a hue the roles do not name, as the hand-made
# Gruvbox scheme this replaced used purple for constants and aqua for tags.

colors:
let
  inherit (colors) base mantle surface overlay text subtext muted accent accent2 error warning success info;
  inherit (colors) brightMagenta brightCyan;

  rule = scope: attrs: { inherit scope; } // attrs;
in
builtins.toJSON {
  name = "Dotfiles";
  author = "Generated by modules/theme from the palette in home.nix";

  globals = {
    background = base;
    foreground = text;
    caret = accent;
    invisibles = overlay;
    line_highlight = surface;
    selection = overlay;
    selection_border = overlay;
    inactive_selection = surface;
    misspelling = error;
    gutter = base;
    gutter_foreground = muted;
    gutter_foreground_highlight = subtext;
    guide = surface;
    active_guide = overlay;
    stack_guide = surface;
    find_highlight = warning;
    find_highlight_foreground = base;
    highlight = warning;
    brackets_options = "underline";
    brackets_foreground = accent;
    bracket_contents_options = "underline";
    bracket_contents_foreground = accent;
    tags_options = "stippled_underline";
    tags_foreground = accent;
    accent = accent;
    shadow = "color(${mantle} alpha(0.5))";
    line_diff_added = success;
    line_diff_modified = accent;
    line_diff_deleted = error;
  };

  rules = [
    (rule "comment, punctuation.definition.comment" { foreground = muted; font_style = "italic"; })
    (rule "string" { foreground = success; })
    (rule "constant.character.escape, string.regexp" { foreground = accent; })
    (rule "constant.numeric, constant.language, constant.character, constant.other" { foreground = brightMagenta; })
    (rule "keyword, storage.modifier, keyword.control" { foreground = error; })
    (rule "keyword.operator" { foreground = text; })
    (rule "keyword.control.import, keyword.control.directive, meta.preprocessor" { foreground = brightCyan; })
    (rule "storage.type, entity.name.type, entity.name.class, support.type, support.class, entity.other.inherited-class" { foreground = warning; })
    (rule "entity.name.function, support.function, variable.function" { foreground = success; font_style = "bold"; })
    (rule "variable.parameter" { foreground = accent2; })
    (rule "variable.language, support.constant" { foreground = accent; })
    (rule "variable.other.member, meta.property-name, support.type.property-name" { foreground = accent2; })
    (rule "entity.name.tag" { foreground = brightCyan; })
    (rule "entity.other.attribute-name" { foreground = warning; })
    (rule "punctuation.definition.tag" { foreground = accent2; })
    (rule "entity.name.section, markup.heading" { foreground = success; font_style = "bold"; })
    (rule "markup.bold" { font_style = "bold"; })
    (rule "markup.italic" { font_style = "italic"; })
    (rule "markup.underline.link, markup.link" { foreground = accent2; })
    (rule "markup.raw" { foreground = brightCyan; })
    (rule "markup.quote" { foreground = muted; font_style = "italic"; })
    (rule "markup.list punctuation.definition.list_item" { foreground = accent; })
    (rule "markup.inserted" { foreground = success; })
    (rule "markup.deleted" { foreground = error; })
    (rule "markup.changed" { foreground = accent; })
    (rule "invalid" { foreground = text; background = error; })
    (rule "invalid.deprecated" { foreground = base; background = accent; })
  ];
}
