{ lib }:

# A Telegram Desktop palette (colors.tdesktop-theme) from a resolved theme:
# every key in telegram-keys.nix, painted with the palette's colors.
#
# The alphas are the hand-made theme's, which tdesktop blends over whatever it
# drew beneath. With transparency off a surface is opaque, while a faint
# alpha — a ripple, a shadow, a tint over a photo — is part of what that color
# is and stays.
#
# A reference is written out as the color it names rather than as the name:
# tdesktop resolves a reference while it reads the file, so one that pointed
# further down would pick up the stock color instead.

colors:
let
  inherit (import ./color.nix { inherit lib; }) mix;

  named = colors // { white = "#ffffff"; black = "#000000"; };
  hex = name: named.${name} or (throw "telegram-keys.nix: no color named \"${name}\"");

  opaque = colors.alpha.window >= 1.0;
  paint = value: alpha:
    let kept = if opaque && lib.fromHexString alpha >= 128 then "ff" else alpha;
    in value + lib.optionalString (kept != "ff") kept;

  keys = import ./telegram-keys.nix {
    color = name: alpha: { value = paint (hex name) alpha; };
    mix = from: to: ratio: alpha: { value = paint (mix (hex from) (hex to) ratio) alpha; };
    ref = key: { ref = key; };
  };

  # A reference to a key the table does not set is left for tdesktop, which
  # then uses the stock color for it.
  resolve = spec:
    if spec ? ref then (if keys ? ${spec.ref} then resolve keys.${spec.ref} else spec.ref)
    else spec.value;
in
''
  // Generated by modules/theme/telegram-theme.nix from the palette in home.nix.
''
+ lib.concatStrings (lib.mapAttrsToList (key: spec: "${key}: ${resolve spec};\n") keys)
