#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# The library above the "STAGES" marker came from that skill and has since been
# adapted for this repository; the per-step stages live below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

readonly RECOVERY_REPOSITORY="${RECOVERY_REPOSITORY:-sorrtory/keepass}"
readonly RECOVERY_REPOSITORY_DIR="${RECOVERY_REPOSITORY_DIR:-$HOME/Documents/keepass}"
readonly RECOVERY_DATABASE="${RECOVERY_DATABASE:-Passwords.kdbx}"
readonly RECOVERY_ENTRY="${RECOVERY_ENTRY:-Encryption Keys/sops}"
readonly RECOVERY_ATTACHMENT="${RECOVERY_ATTACHMENT:-keys.txt}"
readonly AGE_KEY_FILE="${AGE_KEY_FILE:-${XDG_CONFIG_HOME:-$HOME/.config}/sops/age/keys.txt}"
readonly AGE_KEY_METADATA_FILE="${AGE_KEY_METADATA_FILE:-${AGE_KEY_FILE}.recovery}"
# The packaged build points both of these at its own store copies; a repository
# checkout falls back to the working tree.
readonly SOPS_CONFIG_LIB="${SOPS_CONFIG_LIB:-$(dirname -- "${BASH_SOURCE[0]}")/../bootstrap/common/sops-config.sh}"
readonly SOPS_CONFIG_FILE="${SOPS_CONFIG_FILE:-$(dirname -- "${BASH_SOURCE[0]}")/../../.sops.yaml}"
RECOVERY_TEMP_DIR=""

# shellcheck disable=SC1090
. "$SOPS_CONFIG_LIB"

cleanup_recovery_temp() {
  if [[ -n "$RECOVERY_TEMP_DIR" && -d "$RECOVERY_TEMP_DIR" ]]; then
    rm -rf -- "$RECOVERY_TEMP_DIR"
  fi
}

trap cleanup_recovery_temp EXIT

die() {
  printf 'recover-age-identity: %s\n' "$1" >&2
  exit 1
}

EXPECTED_AGE_RECIPIENT="$(sops_config_recipient "$SOPS_CONFIG_FILE")" || die \
  'cannot read the configured age recipient'
readonly EXPECTED_AGE_RECIPIENT

file_mode() {
  stat -c '%a' "$1"
}

derived_recipients() {
  age-keygen -y "$1" 2>/dev/null
}

validate_identity() {
  local key_file="$1" mode recipients

  [[ -f "$key_file" && ! -L "$key_file" ]] || return 1
  mode="$(file_mode "$key_file")" || return 1
  [[ "$mode" == '600' ]] || return 1
  recipients="$(derived_recipients "$key_file")" || return 1
  [[ "$recipients" == "$EXPECTED_AGE_RECIPIENT" ]]
}

write_metadata() {
  local key_file="$1" metadata_file="$2" temp_dir="$3"
  local hash metadata_temp

  hash="$(sha256sum "$key_file")"
  hash="${hash%% *}"
  metadata_temp="$temp_dir/recovery-metadata"
  {
    printf 'recipient=%s\n' "$EXPECTED_AGE_RECIPIENT"
    printf 'sha256=%s\n' "$hash"
  } >"$metadata_temp"
  chmod 600 "$metadata_temp"

  mv -f -- "$metadata_temp" "$metadata_file"
}

identity_status() {
  if validate_identity "$AGE_KEY_FILE"; then
    printf 'age identity is recovered and verified\n'
    return
  fi
  printf 'age identity is missing or invalid\n' >&2
  return 1
}

ensure_github_authentication() {
  if gh auth status --hostname github.com >/dev/null 2>&1; then
    say "Already signed in to GitHub."
    return
  fi

  say "Sign in to GitHub to clone $RECOVERY_REPOSITORY."

  # With prompts disabled gh prints the code and URL and waits for approval,
  # leaving the operator to open it on whichever device they like. It also
  # skips "Authenticate Git?", which would only write a ~/.gitconfig that Home
  # Manager later moves aside: the clone and pull below pass gh's credential
  # helper themselves.
  note "Open the URL below on any device and enter the code."
  GH_PROMPT_DISABLED=1 \
    gh auth login --hostname github.com --git-protocol https --web
}

ensure_recovery_repository() {
  local status

  if [[ -d "$RECOVERY_REPOSITORY_DIR/.git" ]]; then
    status="$(git -C "$RECOVERY_REPOSITORY_DIR" status --porcelain)"
    [[ -z "$status" ]] || die "recovery repository has local changes: $RECOVERY_REPOSITORY_DIR"
    say "Updating $RECOVERY_REPOSITORY_DIR."
    # A clone made by an earlier, interrupted run has an HTTPS remote and no
    # stored Git credential, so authenticate the pull the way gh repo clone
    # does. A remote over SSH ignores the helper.
    git -C "$RECOVERY_REPOSITORY_DIR" \
      -c credential.helper= -c 'credential.helper=!gh auth git-credential' \
      pull --ff-only
    return
  fi

  [[ ! -e "$RECOVERY_REPOSITORY_DIR" ]] || die \
    "recovery path exists but is not a Git repository: $RECOVERY_REPOSITORY_DIR"
  mkdir -p "$(dirname -- "$RECOVERY_REPOSITORY_DIR")"
  gh repo clone "$RECOVERY_REPOSITORY" "$RECOVERY_REPOSITORY_DIR"
}

# explain_entry_path prints how keepassxc-cli resolves an entry, since a wrong
# RECOVERY_ENTRY is the likeliest reason the export failed.
explain_entry_path() {
  warn "RECOVERY_ENTRY may be wrong: use the full path without the root group."
  note "List paths with: keepassxc-cli ls -R -f $1"
}

restore_identity() {
  local database key_dir key_temp recipients

  database="$RECOVERY_REPOSITORY_DIR/$RECOVERY_DATABASE"
  [[ -f "$database" && ! -L "$database" ]] || die \
    "KeePassXC database not found: $database"

  key_dir="$(dirname -- "$AGE_KEY_FILE")"
  umask 077
  mkdir -p "$key_dir"
  chmod 700 "$key_dir"

  if [[ -e "$AGE_KEY_FILE" || -L "$AGE_KEY_FILE" ]]; then
    validate_identity "$AGE_KEY_FILE" || die \
      "existing age identity is invalid or has the wrong recipient; refusing to overwrite it"
    RECOVERY_TEMP_DIR="$(mktemp -d "$key_dir/.recover-age-identity.XXXXXX")"
    write_metadata "$AGE_KEY_FILE" "$AGE_KEY_METADATA_FILE" "$RECOVERY_TEMP_DIR"
    rm -rf -- "$RECOVERY_TEMP_DIR"
    RECOVERY_TEMP_DIR=""
    say "The existing age identity is valid."
    return
  fi

  RECOVERY_TEMP_DIR="$(mktemp -d "$key_dir/.recover-age-identity.XXXXXX")"
  key_temp="$RECOVERY_TEMP_DIR/keys.txt"
  if ! keepassxc-cli attachment-export \
    "$database" "$RECOVERY_ENTRY" "$RECOVERY_ATTACHMENT" "$key_temp"; then
    explain_entry_path "$database"
    die "cannot export $RECOVERY_ATTACHMENT from $RECOVERY_ENTRY"
  fi
  chmod 600 "$key_temp"

  recipients="$(derived_recipients "$key_temp")" || die \
    'the KeePassXC attachment is not a valid age identity file'
  [[ "$recipients" == "$EXPECTED_AGE_RECIPIENT" ]] || die \
    'the KeePassXC attachment does not match the configured age recipient'

  ln "$key_temp" "$AGE_KEY_FILE" || die \
    "cannot install the age identity without overwriting: $AGE_KEY_FILE"
  write_metadata "$AGE_KEY_FILE" "$AGE_KEY_METADATA_FILE" "$RECOVERY_TEMP_DIR"
  rm -rf -- "$RECOVERY_TEMP_DIR"
  RECOVERY_TEMP_DIR=""
  say "Restored $AGE_KEY_FILE."
}

case "${1:-install}" in
status)
  [[ $# -eq 1 ]] || die 'usage: recover-age-identity [status|install]'
  identity_status
  exit
  ;;
install)
  [[ $# -le 1 ]] || die 'usage: recover-age-identity [status|install]'
  ;;
*)
  die 'usage: recover-age-identity [status|install]'
  ;;
esac

if validate_identity "$AGE_KEY_FILE"; then
  key_dir="$(dirname -- "$AGE_KEY_FILE")"
  umask 077
  mkdir -p "$key_dir"
  chmod 700 "$key_dir"
  RECOVERY_TEMP_DIR="$(mktemp -d "$key_dir/.recover-age-identity.XXXXXX")"
  write_metadata "$AGE_KEY_FILE" "$AGE_KEY_METADATA_FILE" "$RECOVERY_TEMP_DIR"
  rm -rf -- "$RECOVERY_TEMP_DIR"
  RECOVERY_TEMP_DIR=""
  printf 'age identity is already recovered and verified\n'
  exit
fi

TOTAL_STAGES=2

stage "Download the vault"
ensure_github_authentication
ensure_recovery_repository

stage "Unlock the vault"
restore_identity

finish
