#!/usr/bin/env bash
#
# vpn — run one program inside a WireGuard network namespace.
#
# The host keeps its own routing. A process placed in this namespace has no
# route anywhere except the tunnel, which is the property that makes it work
# for programs that ignore proxy settings and for protocols a proxy cannot
# carry. See .scratch/vpn-command/spec.md, and docs/DECISIONS.md for why this
# exists alongside the sing-box proxy rather than instead of it.

set -euo pipefail

NS="vpn"
WG_IF="wg-vpn"
VETH_HOST="veth-vpn"
VETH_NS="veth-vpn-ns"

VETH_HOST_IP4="10.200.200.1"
VETH_NS_IP4="10.200.200.2"
VETH_SUBNET4="10.200.200.0/24"

NETNS_ETC="/etc/netns/${NS}"
STATE_DIR="/run/vpn-command"
WAN_IF_FILE="${STATE_DIR}/wan-if"
FORWARD_FILE="${STATE_DIR}/ip-forward-was"
LOCK_FILE="/run/vpn-command.lock"

# Used only when the tunnel configuration names no DNS of its own.
FALLBACK_DNS="1.1.1.1"

if [[ -t 2 ]] && command -v tput >/dev/null 2>&1; then
  C_RED="$(tput setaf 1)"; C_GREEN="$(tput setaf 2)"
  C_YELLOW="$(tput setaf 3)"; C_RESET="$(tput sgr0)"
else
  C_RED=""; C_GREEN=""; C_YELLOW=""; C_RESET=""
fi

ok()   { printf '%s%s%s\n' "$C_GREEN"  "$*" "$C_RESET" >&2; }
warn() { printf '%s%s%s\n' "$C_YELLOW" "$*" "$C_RESET" >&2; }
die()  { printf '%s%s%s\n' "$C_RED" "Error: $*" "$C_RESET" >&2; exit 1; }

usage() {
  cat >&2 <<EOF
Usage:
  vpn [--config <path>] <command> [args...]   run a command inside the tunnel
  vpn --test                                  report the address seen from inside
  vpn --clean                                 tear the namespace down
  vpn --help

The namespace is created on first use and removed once nothing is left inside
it, so there is no separate up or down step. The host's routing, firewall and
resolver configuration are never modified outside the namespace.
EOF
}

# ─── Invoking user ───────────────────────────────────────────────────────────
# Captured before escalating, because after sudo none of it is knowable: SUDO_*
# is not set when already root, and $HOME belongs to root.

capture_user_context() {
  VPN_RUN_USER="${VPN_RUN_USER:-$(id -un)}"
  VPN_RUN_UID="${VPN_RUN_UID:-$(id -u)}"
  VPN_RUN_GID="${VPN_RUN_GID:-$(id -g)}"
  VPN_RUN_HOME="${VPN_RUN_HOME:-$HOME}"
  export VPN_RUN_USER VPN_RUN_UID VPN_RUN_GID VPN_RUN_HOME
}

# The payload must see the environment it would have seen without this command
# wrapping it — not a list of variables someone remembered to preserve. `export
# -p` quotes values safely and bash can source the result back. The readonly
# shell variables are dropped because sourcing them fails.
capture_environment() {
  local dir="${XDG_RUNTIME_DIR:-/tmp}"
  VPN_ENV_FILE="$(mktemp "${dir}/vpn-env.XXXXXX")"
  chmod 600 "$VPN_ENV_FILE"
  export -p \
    | grep -Ev '^declare -x (BASHOPTS|SHELLOPTS|UID|EUID|PPID)=' \
    > "$VPN_ENV_FILE"
  export VPN_ENV_FILE
}

reexec_as_root() {
  [[ "${EUID:-$(id -u)}" -eq 0 ]] && return 0
  command -v sudo >/dev/null 2>&1 || die "sudo not found, and this needs root to create a namespace"

  capture_user_context
  capture_environment

  # PATH is passed explicitly because sudo replaces it with secure_path, and
  # this script's own dependencies come from the Nix profile that PATH names.
  exec sudo \
    VPN_RUN_USER="$VPN_RUN_USER" \
    VPN_RUN_UID="$VPN_RUN_UID" \
    VPN_RUN_GID="$VPN_RUN_GID" \
    VPN_RUN_HOME="$VPN_RUN_HOME" \
    VPN_ENV_FILE="$VPN_ENV_FILE" \
    VPN_PATH="$PATH" \
    "$0" "$@"
}

# ─── Tunnel configuration ────────────────────────────────────────────────────

config_field() {
  local section="$1" key="$2"
  awk -v sec="$section" -v key="$key" '
    /^[[:space:]]*\[/ { insec = ($0 ~ "^[[:space:]]*\\["sec"\\]"); next }
    insec && $0 ~ "^[[:space:]]*"key"[[:space:]]*=" {
      sub(/^[^=]*=[[:space:]]*/, "")
      gsub(/^[[:space:]]+|[[:space:]]+$/, "")
      print; exit
    }
  ' "$WG_CONF"
}

require_config() {
  [[ -r "$WG_CONF" ]] || die "tunnel configuration not readable: $WG_CONF
It is a sops-nix secret, materialized by Home Manager activation. If this is a
fresh boot, activate first: ./scripts/bootstrap.sh install home-manager"
}

# ─── Namespace ───────────────────────────────────────────────────────────────

netns_exists() { ip netns list | awk '{print $1}' | grep -qx "$NS"; }

netns_pid_count() {
  local pids
  pids="$(ip netns pids "$NS" 2>/dev/null || true)"
  [[ -z "$pids" ]] && { echo 0; return; }
  printf '%s\n' "$pids" | grep -c .
}

detect_wan_if() {
  ip route get 1.1.1.1 2>/dev/null \
    | awk '{for (i = 1; i <= NF; i++) if ($i == "dev") { print $(i + 1); exit }}'
}

write_resolv_conf() {
  local dns
  dns="$(config_field Interface DNS || true)"
  mkdir -p "$NETNS_ETC"

  {
    echo "# generated by the vpn command; scoped to the $NS namespace"
    if [[ -n "$dns" ]]; then
      # The configuration may list several, comma separated, and may include
      # search domains alongside addresses.
      printf '%s\n' "$dns" | tr ',' '\n' | while read -r entry; do
        entry="$(echo "$entry" | xargs)"
        [[ -n "$entry" ]] || continue
        if [[ "$entry" =~ ^[0-9a-fA-F:.]+$ ]]; then
          echo "nameserver $entry"
        else
          echo "search $entry"
        fi
      done
    else
      echo "nameserver $FALLBACK_DNS"
    fi
  } > "${NETNS_ETC}/resolv.conf"

  if [[ -n "$dns" ]]; then
    ok "DNS from the tunnel configuration"
  else
    warn "Tunnel configuration names no DNS; using $FALLBACK_DNS"
  fi
}

setup_namespace() {
  require_config

  local key address peer_key psk endpoint
  key="$(config_field Interface PrivateKey)"
  address="$(config_field Interface Address)"
  peer_key="$(config_field Peer PublicKey)"
  psk="$(config_field Peer PresharedKey || true)"
  endpoint="$(config_field Peer Endpoint)"

  [[ -n "$key" && -n "$address" && -n "$peer_key" && -n "$endpoint" ]] \
    || die "missing PrivateKey, Address, PublicKey or Endpoint in $WG_CONF"

  local endpoint_host endpoint_port
  if [[ "$endpoint" =~ ^\[(.+)\]:([0-9]+)$ ]]; then
    endpoint_host="${BASH_REMATCH[1]}"; endpoint_port="${BASH_REMATCH[2]}"
    die "IPv6 endpoints are not supported yet: $endpoint"
  elif [[ "$endpoint" =~ ^([^:]+):([0-9]+)$ ]]; then
    endpoint_host="${BASH_REMATCH[1]}"; endpoint_port="${BASH_REMATCH[2]}"
  else
    die "unrecognized endpoint: $endpoint"
  fi

  # An endpoint given as a name has to be resolved out here: inside the
  # namespace the only route is the tunnel, and the tunnel needs this address
  # to exist.
  if [[ ! "$endpoint_host" =~ ^[0-9.]+$ ]]; then
    endpoint_host="$(getent ahostsv4 "$endpoint_host" | awk '{print $1; exit}')"
    [[ -n "$endpoint_host" ]] || die "could not resolve endpoint host in $endpoint"
  fi

  mkdir -p "$STATE_DIR"

  ip netns add "$NS"
  ip -n "$NS" link set lo up

  # Created out here and moved in, so its own encrypted packets leave through
  # the host's real connection rather than trying to route through themselves.
  ip link add dev "$WG_IF" type wireguard
  ip link set dev "$WG_IF" netns "$NS"

  local psk_args=()
  [[ -n "$psk" ]] && psk_args=(preshared-key /dev/fd/4)

  # Keys go in on file descriptors. A command line is world-readable through
  # /proc, and an environment variable is nearly as bad.
  ip netns exec "$NS" \
    wg set "$WG_IF" \
      private-key /dev/fd/3 \
      peer "$peer_key" \
        "${psk_args[@]}" \
        endpoint "${endpoint_host}:${endpoint_port}" \
        allowed-ips 0.0.0.0/0,::/0 \
        persistent-keepalive 25 \
    3<<<"$key" 4<<<"${psk:-}"

  local addr
  while read -r addr; do
    [[ -n "$addr" ]] || continue
    if [[ "$addr" == *:* ]]; then
      ip -n "$NS" -6 addr replace "$addr" dev "$WG_IF" 2>/dev/null || true
    else
      [[ "$addr" == */* ]] || addr="${addr}/32"
      ip -n "$NS" addr replace "$addr" dev "$WG_IF"
    fi
  done < <(printf '%s\n' "$address" | tr ',' '\n' | xargs -n1 2>/dev/null || true)

  ip -n "$NS" link set "$WG_IF" up

  ip link add "$VETH_HOST" type veth peer name "$VETH_NS"
  ip link set "$VETH_HOST" up
  ip addr replace "${VETH_HOST_IP4}/24" dev "$VETH_HOST"
  ip link set "$VETH_NS" netns "$NS"
  ip -n "$NS" addr replace "${VETH_NS_IP4}/24" dev "$VETH_NS"
  ip -n "$NS" link set "$VETH_NS" up

  # Recorded so teardown can leave forwarding exactly as it was found rather
  # than assuming this command turned it on.
  sysctl -n net.ipv4.ip_forward > "$FORWARD_FILE"
  sysctl -wq net.ipv4.ip_forward=1

  local wan
  wan="$(detect_wan_if)"
  [[ -n "$wan" ]] || die "could not determine the WAN interface"
  echo "$wan" > "$WAN_IF_FILE"

  iptables -w -t nat -A POSTROUTING -s "$VETH_SUBNET4" -o "$wan" -j MASQUERADE
  iptables -w -A FORWARD -i "$VETH_HOST" -j ACCEPT
  iptables -w -A FORWARD -o "$VETH_HOST" -j ACCEPT

  # The tunnel's own traffic goes out through the veth; everything else the
  # namespace does goes through the tunnel.
  ip -n "$NS" route replace "${endpoint_host}/32" via "$VETH_HOST_IP4" dev "$VETH_NS"
  ip -n "$NS" route replace default dev "$WG_IF"

  # No IPv6 route is added at all. The veth carries none and the tunnel is not
  # known to, so leaving v6 unroutable keeps it from escaping untunneled.

  write_resolv_conf
  ok "Namespace '$NS' is up"
}

teardown_namespace() {
  local wan=""
  [[ -s "$WAN_IF_FILE" ]] && wan="$(cat "$WAN_IF_FILE")"
  [[ -n "$wan" ]] || wan="$(detect_wan_if || true)"

  if [[ -n "$wan" ]]; then
    iptables -w -t nat -D POSTROUTING -s "$VETH_SUBNET4" -o "$wan" -j MASQUERADE 2>/dev/null || true
  fi
  iptables -w -D FORWARD -i "$VETH_HOST" -j ACCEPT 2>/dev/null || true
  iptables -w -D FORWARD -o "$VETH_HOST" -j ACCEPT 2>/dev/null || true

  if [[ -s "$FORWARD_FILE" ]]; then
    sysctl -wq "net.ipv4.ip_forward=$(cat "$FORWARD_FILE")" 2>/dev/null || true
  fi

  ip -n "$NS" link del "$WG_IF" 2>/dev/null || true
  ip link del "$WG_IF" 2>/dev/null || true
  ip link del "$VETH_HOST" 2>/dev/null || true
  ip netns del "$NS" 2>/dev/null || true

  rm -rf "$NETNS_ETC" "$STATE_DIR"
  ok "Namespace '$NS' is down"
}

# A namespace with no WireGuard interface in it is the wreckage of a run that
# died during setup. Reusing it would produce a namespace with no route out,
# which looks like a network fault rather than the leftover it is.
namespace_is_healthy() {
  ip -n "$NS" link show "$WG_IF" >/dev/null 2>&1
}

ensure_namespace() {
  if netns_exists; then
    if namespace_is_healthy; then
      return 0
    fi
    warn "Found a half-built namespace from an earlier run; rebuilding it"
    teardown_namespace
  fi
  setup_namespace
}

# ─── Payload ─────────────────────────────────────────────────────────────────

run_payload() {
  local env_file="${VPN_ENV_FILE:-}"
  [[ -n "$env_file" && -r "$env_file" ]] \
    || die "the captured environment is missing; run this as your own user, not through sudo"

  # setpriv drops privilege without touching the environment, which is what
  # lets the payload keep the session it was started from. runuser and su both
  # rebuild the environment from login defaults instead.
  ip netns exec "$NS" \
    setpriv --reuid "$VPN_RUN_UID" --regid "$VPN_RUN_GID" --init-groups -- \
    bash -c '
      set -euo pipefail
      env_file="$1"; shift
      # shellcheck disable=SC1090
      source "$env_file"
      rm -f "$env_file"
      exec "$@"
    ' vpn-payload "$env_file" "$@"
}

run_test() {
  local inside
  inside="$(ip netns exec "$NS" curl -fsS --max-time 10 https://ident.me 2>/dev/null || true)"
  if [[ -n "$inside" ]]; then
    ok "Address seen from inside the tunnel: $inside"
  else
    die "no connectivity inside the namespace"
  fi

  echo >&2 "Resolver inside the namespace:"
  ip netns exec "$NS" sed 's/^/  /' /etc/resolv.conf >&2 2>/dev/null || true
}

# ─── Arguments ───────────────────────────────────────────────────────────────

DO_CLEAN=0
DO_TEST=0
WG_CONF=""
ORIGINAL_ARGS=("$@")

while [[ $# -gt 0 ]]; do
  case "$1" in
    -h|--help) usage; exit 0 ;;
    -C|--config)
      [[ $# -ge 2 ]] || die "$1 needs a path"
      WG_CONF="$2"; shift 2 ;;
    -c|--clean) DO_CLEAN=1; shift ;;
    -t|--test)  DO_TEST=1; shift ;;
    --) shift; break ;;
    -*) die "unknown option: $1" ;;
    *) break ;;
  esac
done

capture_user_context
: "${WG_CONF:=${VPN_RUN_HOME}/.config/sops-nix/secrets/wireguard/extra.conf}"

if [[ "$DO_CLEAN" -eq 0 && "$DO_TEST" -eq 0 && $# -eq 0 ]]; then
  usage
  exit 1
fi

reexec_as_root "${ORIGINAL_ARGS[@]}"
[[ "${EUID:-$(id -u)}" -eq 0 ]] || die "must run as root"
[[ -n "${VPN_PATH:-}" ]] && export PATH="$VPN_PATH"

exec 9>"$LOCK_FILE"
flock 9

if [[ "$DO_CLEAN" -eq 1 ]]; then
  netns_exists || { warn "Namespace '$NS' does not exist"; exit 0; }
  teardown_namespace
  exit 0
fi

ensure_namespace

if [[ "$DO_TEST" -eq 1 ]]; then
  run_test
  status=0
else
  # The lock is released for the duration of the payload: it may run for hours,
  # and a second invocation must be able to join the namespace meanwhile.
  flock -u 9
  status=0
  run_payload "$@" || status=$?
  flock 9
fi

# Whoever leaves last turns out the lights. Tearing down while another payload
# is still inside would cut off a running program.
remaining="$(netns_pid_count)"
if [[ "$remaining" -eq 0 ]]; then
  teardown_namespace
else
  warn "Leaving namespace '$NS' up: $remaining process(es) still inside"
fi

exit "$status"
