# Generated by modules/programs/vpnized-apps and installed by the apparmor
# bootstrap phase. A user-namespace allowance for one exact executable, NOT an
# application confinement profile. See docs/VESKTOP-APPARMOR.md.
abi <abi/4.0>,
include <tunables/global>

profile @name@ @executable@ flags=(unconfined) {
  userns,
}
