#!/usr/bin/env bash

set -euo pipefail

BOOTSTRAP_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
readonly BOOTSTRAP_DIR
# shellcheck disable=SC1091
. "$BOOTSTRAP_DIR/common/phase.sh"

# Overridable so tests never read or change the host's policy. The profiles
# are generated by Home Manager from the exact packages in use.
readonly PROFILE_SOURCE="${BOOTSTRAP_APPARMOR_SOURCE:-${XDG_DATA_HOME:-$HOME/.local/share}/dotfiles/apparmor}"
readonly PROFILE_TARGET="${BOOTSTRAP_APPARMOR_TARGET:-/etc/apparmor.d}"
readonly USERNS_RESTRICTION="${BOOTSTRAP_USERNS_RESTRICTION:-/proc/sys/kernel/apparmor_restrict_unprivileged_userns}"

# The allowances exist only for Ubuntu's restriction on unprivileged user
# namespaces. Where it is off, installing them would add policy for nothing.
userns_restricted() {
  [[ -r "$USERNS_RESTRICTION" && "$(<"$USERNS_RESTRICTION")" == 1 ]]
}

profiles_in() {
  local profile

  shopt -s nullglob
  for profile in "$1"/dotfiles-*; do
    echo "$profile"
  done
  shopt -u nullglob
}

remove_profile() {
  phase_info "removing ${1##*/}..."
  # Unloading fails harmlessly when the profile was never loaded.
  sudo apparmor_parser --remove "$1" 2>/dev/null || true
  sudo rm -f -- "$1"
}

check() {
  local name profile
  local stale=0

  if ! userns_restricted; then
    phase_info 'unprivileged user namespaces are not restricted; no profiles needed'
    return
  fi
  if [[ ! -d "$PROFILE_SOURCE" ]]; then
    phase_info 'no generated profiles; run the home-manager phase first'
    return 1
  fi

  require_commands cmp
  while IFS= read -r profile; do
    name="${profile##*/}"
    if ! cmp -s -- "$profile" "$PROFILE_TARGET/$name"; then
      phase_info "$name is missing or stale"
      stale=1
    fi
  done < <(profiles_in "$PROFILE_SOURCE")
  while IFS= read -r profile; do
    name="${profile##*/}"
    if [[ ! -e "$PROFILE_SOURCE/$name" ]]; then
      phase_info "$name is installed but no longer generated"
      stale=1
    fi
  done < <(profiles_in "$PROFILE_TARGET")

  if ((stale)); then
    return 1
  fi
  phase_info 'installed profiles match the activated configuration'
}

# shellcheck disable=SC2032 # the phase contract names this function install
install() {
  local name profile
  local -a generated=()

  if [[ $EUID -eq 0 ]]; then
    phase_error 'run this phase as the target user, not as root'
    return 1
  fi
  if [[ ! -d "$PROFILE_SOURCE" ]]; then
    phase_error 'no generated profiles; run the home-manager phase first'
    return 1
  fi

  require_commands sudo
  mapfile -t generated < <(profiles_in "$PROFILE_SOURCE")

  # Validate every profile before changing any installed policy.
  for profile in "${generated[@]}"; do
    sudo apparmor_parser --skip-kernel-load --skip-read-cache "$profile"
  done
  for profile in "${generated[@]}"; do
    name="${profile##*/}"
    phase_info "installing $name..."
    # shellcheck disable=SC2033 # coreutils install(1), not this phase's install()
    sudo install -o root -g root -m 0644 -- "$profile" "$PROFILE_TARGET/$name"
    sudo apparmor_parser --replace "$PROFILE_TARGET/$name"
  done
  while IFS= read -r profile; do
    if [[ ! -e "$PROFILE_SOURCE/${profile##*/}" ]]; then
      remove_profile "$profile"
    fi
  done < <(profiles_in "$PROFILE_TARGET")
  phase_info 'restart tunneled programs and Vesktop to use the new profiles'
}

is_uninstalled() {
  [[ -z "$(profiles_in "$PROFILE_TARGET")" ]]
}

uninstall() {
  local profile

  if [[ $EUID -eq 0 ]]; then
    phase_error 'run this phase as the target user, not as root'
    return 1
  fi

  require_commands sudo
  while IFS= read -r profile; do
    remove_profile "$profile"
  done < <(profiles_in "$PROFILE_TARGET")
}

phase_main "$@"
